### ISSUE TITLE
Error when following readme

### ISSUE THREAD

**Issue by yovanoc** [Ehstrali/TouchEmu#14]
Hello, there an error in the readme. when we clone, install dependencies, gulp and start, we have this error:
<img width="925" alt="screen shot 2017-12-15 at 21 42 01" src="https://user-images.githubusercontent.com/7302317/34059789-f0e76ec6-e1e0-11e7-95bd-3d9422c73acb.png">

**Comment by Ehstrali** [comment]
Je vais essayer de corriger ça en attendant tu peux télécharger l’app qui ne devrait pas bug [ici](https://github.com/Ehstrali/TouchEmu/releases/tag/3.4.4)

**Comment by yovanoc** [comment]
Pas de soucis :)

**Comment by jug-eum** [comment]
Hello, pas de news à propos de cette erreur ?
Impossible de lancer depuis les sources ...  (╯°□°）╯︵ ┻━┻

**Comment by HorlogeSkynet** [comment]
J'ai effectivement la même c'est très bizarre...
Apparemment rien n'aurait été cassé sur ce repo' (mais il faut re-vérifier). Serait-ce à cause d'un module dont une version mineure aurait été publiée récemment ?

**Comment by Ehstrali** [comment]
J'ai trouvé le prob on peut le resoudre avec ça:
 'sortablejs': { defaultExtension: 'js', main: './Sortable.min.js' }
Je fait le commit dans quelques sec

**Comment by Ehstrali** [comment]
Problème résolu je ferme !
